[2023-12-27 18:15:45,392] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.extraer_data manual__2023-12-27T18:15:41.747249+00:00 [queued]>
[2023-12-27 18:15:45,414] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.extraer_data manual__2023-12-27T18:15:41.747249+00:00 [queued]>
[2023-12-27 18:15:45,415] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:15:45,416] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-27 18:15:45,417] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:15:45,452] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extraer_data> on 2023-12-27 18:15:41.747249+00:00
[2023-12-27 18:15:45,461] {standard_task_runner.py:52} INFO - Started process 14402 to run task
[2023-12-27 18:15:45,469] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL2', 'extraer_data', 'manual__2023-12-27T18:15:41.747249+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather2.py', '--cfg-path', '/tmp/tmpdz3yvhs5', '--error-file', '/tmp/tmp58si7f4j']
[2023-12-27 18:15:45,472] {standard_task_runner.py:80} INFO - Job 114: Subtask extraer_data
[2023-12-27 18:15:45,733] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL2.extraer_data manual__2023-12-27T18:15:41.747249+00:00 [running]> on host 44a36bef83ad
[2023-12-27 18:15:45,878] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-27 18:15:45,988] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL2
AIRFLOW_CTX_TASK_ID=extraer_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T18:15:41.747249+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-27T18:15:41.747249+00:00
[2023-12-27 18:15:45,991] {logging_mixin.py:115} INFO - Adquiriendo data para la fecha: 2023-12-27 18
[2023-12-27 18:15:47,105] {logging_mixin.py:115} INFO - Datos adquiridos!
[2023-12-27 18:15:47,115] {python.py:173} INFO - Done. Returned value was: None
[2023-12-27 18:15:47,145] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL2, task_id=extraer_data, execution_date=20231227T181541, start_date=20231227T181545, end_date=20231227T181547
[2023-12-27 18:15:47,217] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-27 18:15:47,360] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
