[2023-12-27 18:20:38,267] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.conexion_BD manual__2023-12-27T18:20:23.365777+00:00 [queued]>
[2023-12-27 18:20:38,321] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.conexion_BD manual__2023-12-27T18:20:23.365777+00:00 [queued]>
[2023-12-27 18:20:38,323] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:20:38,325] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-27 18:20:38,326] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:20:38,416] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conexion_BD> on 2023-12-27 18:20:23.365777+00:00
[2023-12-27 18:20:38,432] {standard_task_runner.py:52} INFO - Started process 14716 to run task
[2023-12-27 18:20:38,456] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL2', 'conexion_BD', 'manual__2023-12-27T18:20:23.365777+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather2.py', '--cfg-path', '/tmp/tmpd79vso8q', '--error-file', '/tmp/tmpmdkd5631']
[2023-12-27 18:20:38,466] {standard_task_runner.py:80} INFO - Job 126: Subtask conexion_BD
[2023-12-27 18:20:38,745] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL2.conexion_BD manual__2023-12-27T18:20:23.365777+00:00 [running]> on host 44a36bef83ad
[2023-12-27 18:20:38,871] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-27 18:20:39,011] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL2
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T18:20:23.365777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-27T18:20:23.365777+00:00
[2023-12-27 18:20:39,014] {logging_mixin.py:115} INFO - Conectandose a la DB en la fecha: 2023-12-27 18
[2023-12-27 18:20:40,225] {logging_mixin.py:115} INFO - <connection object at 0x7fd719ce0440; dsn: 'user=juliocfurtado93_coderhouse password=xxx dbname=data-engineer-database host=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com port=5439', closed: 0>
[2023-12-27 18:20:40,226] {logging_mixin.py:115} INFO - Conexion a RedShift exitosa!
[2023-12-27 18:20:40,227] {python.py:173} INFO - Done. Returned value was: None
[2023-12-27 18:20:40,268] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL2, task_id=conexion_BD, execution_date=20231227T182023, start_date=20231227T182038, end_date=20231227T182040
[2023-12-27 18:20:40,315] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-27 18:20:40,414] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
