[2023-12-20 00:36:34,393] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL.transformar_data scheduled__2023-12-19T00:00:00+00:00 [queued]>
[2023-12-20 00:36:34,440] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL.transformar_data scheduled__2023-12-19T00:00:00+00:00 [queued]>
[2023-12-20 00:36:34,441] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-20 00:36:34,442] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-20 00:36:34,444] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-20 00:36:34,503] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-19 00:00:00+00:00
[2023-12-20 00:36:34,517] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2023-12-20 00:36:34,542] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL', 'transformar_data', 'scheduled__2023-12-19T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather.py', '--cfg-path', '/tmp/tmp95psa_zd', '--error-file', '/tmp/tmpztq2gqv_']
[2023-12-20 00:36:34,548] {standard_task_runner.py:80} INFO - Job 58: Subtask transformar_data
[2023-12-20 00:36:35,053] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL.transformar_data scheduled__2023-12-19T00:00:00+00:00 [running]> on host 44a36bef83ad
[2023-12-20 00:36:35,920] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-20 00:36:36,242] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-19T00:00:00+00:00
[2023-12-20 00:36:36,245] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-19 0
[2023-12-20 00:36:36,390] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:93 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,402] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:94 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,419] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:95 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,453] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:98 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,470] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:99 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,491] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:100 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,505] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:5047 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-20 00:36:36,596] {python.py:173} INFO - Done. Returned value was: None
[2023-12-20 00:36:36,658] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL, task_id=transformar_data, execution_date=20231219T000000, start_date=20231220T003634, end_date=20231220T003636
[2023-12-20 00:36:36,752] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-20 00:36:37,271] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
