[2023-12-27 14:37:14,923] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL.transformar_data scheduled__2023-12-26T00:00:00+00:00 [queued]>
[2023-12-27 14:37:15,091] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL.transformar_data scheduled__2023-12-26T00:00:00+00:00 [queued]>
[2023-12-27 14:37:15,175] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 14:37:15,248] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-27 14:37:15,267] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 14:37:15,469] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transformar_data> on 2023-12-26 00:00:00+00:00
[2023-12-27 14:37:15,534] {standard_task_runner.py:52} INFO - Started process 192 to run task
[2023-12-27 14:37:15,576] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL', 'transformar_data', 'scheduled__2023-12-26T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather.py', '--cfg-path', '/tmp/tmprl1d9wk5', '--error-file', '/tmp/tmpt2styhdi']
[2023-12-27 14:37:15,592] {standard_task_runner.py:80} INFO - Job 67: Subtask transformar_data
[2023-12-27 14:37:16,466] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL.transformar_data scheduled__2023-12-26T00:00:00+00:00 [running]> on host 44a36bef83ad
[2023-12-27 14:37:16,822] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-27 14:37:17,107] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL
AIRFLOW_CTX_TASK_ID=transformar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-26T00:00:00+00:00
[2023-12-27 14:37:17,111] {logging_mixin.py:115} INFO - Transformando la data para la fecha: 2023-12-26 0
[2023-12-27 14:37:17,252] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:93 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,267] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:94 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,281] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:95 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,300] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:98 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,315] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:99 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,328] {logging_mixin.py:115} WARNING - /opt/***/dags/ETL_OpenWeather.py:100 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,340] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:5047 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-12-27 14:37:17,360] {python.py:173} INFO - Done. Returned value was: None
[2023-12-27 14:37:17,419] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL, task_id=transformar_data, execution_date=20231226T000000, start_date=20231227T143715, end_date=20231227T143717
[2023-12-27 14:37:17,519] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-27 14:37:17,945] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
