[2023-12-27 18:11:49,960] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.extraer_data manual__2023-12-27T18:11:45.832652+00:00 [queued]>
[2023-12-27 18:11:49,985] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.extraer_data manual__2023-12-27T18:11:45.832652+00:00 [queued]>
[2023-12-27 18:11:49,986] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:11:49,987] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-27 18:11:49,987] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:11:50,022] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extraer_data> on 2023-12-27 18:11:45.832652+00:00
[2023-12-27 18:11:50,033] {standard_task_runner.py:52} INFO - Started process 14159 to run task
[2023-12-27 18:11:50,041] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL2', 'extraer_data', 'manual__2023-12-27T18:11:45.832652+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather2.py', '--cfg-path', '/tmp/tmp62fs1h30', '--error-file', '/tmp/tmpysmw21oa']
[2023-12-27 18:11:50,044] {standard_task_runner.py:80} INFO - Job 109: Subtask extraer_data
[2023-12-27 18:11:50,244] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL2.extraer_data manual__2023-12-27T18:11:45.832652+00:00 [running]> on host 44a36bef83ad
[2023-12-27 18:11:50,365] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-27 18:11:50,518] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL2
AIRFLOW_CTX_TASK_ID=extraer_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T18:11:45.832652+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-27T18:11:45.832652+00:00
[2023-12-27 18:11:50,522] {logging_mixin.py:115} INFO - Adquiriendo data para la fecha: 2023-12-27 18
[2023-12-27 18:11:51,642] {logging_mixin.py:115} INFO - Datos adquiridos!
[2023-12-27 18:11:51,657] {python.py:173} INFO - Done. Returned value was: None
[2023-12-27 18:11:51,701] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL2, task_id=extraer_data, execution_date=20231227T181145, start_date=20231227T181149, end_date=20231227T181151
[2023-12-27 18:11:51,781] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-27 18:11:51,887] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
